### ISSUE TITLE
쿠키 접근 이슈

### ISSUE THREAD

**Issue by crispebble** [YooHayoung/Come-On#40]
쿠키 접근 이슈 발생
요청하는 측과 응답하는 측의 domain이 달라 발생하는 문제.

서버에서 쿠키에 도메인을 설정하고 전달해도, 웹 상에서 해당 토큰에 대한 접근을 막고 max-age를 0으로 세팅해버린다..

**Comment by cares0** [comment]
HTTPS 적용하면서 해결 완료
